export const rawData = [
  // North America
  { tool: "BigQuery", category: "Data Warehouse", region: "North America", segment: "Small", companies: 469 },
  { tool: "BigQuery", category: "Data Warehouse", region: "North America", segment: "Mid", companies: 911 },
  { tool: "BigQuery", category: "Data Warehouse", region: "North America", segment: "Enterprise", companies: 414 },
  { tool: "Snowflake", category: "Data Warehouse", region: "North America", segment: "Enterprise", companies: 1554 },
  { tool: "Snowflake", category: "Data Warehouse", region: "North America", segment: "Small", companies: 1989 },
  { tool: "Snowflake", category: "Data Warehouse", region: "North America", segment: "Mid", companies: 3896 },
  { tool: "Redshift", category: "Data Warehouse", region: "North America", segment: "Enterprise", companies: 742 },
  { tool: "Redshift", category: "Data Warehouse", region: "North America", segment: "Small", companies: 919 },
  { tool: "Redshift", category: "Data Warehouse", region: "North America", segment: "Mid", companies: 1828 },
  { tool: "Databricks", category: "Data Warehouse", region: "North America", segment: "Enterprise", companies: 1185 },
  { tool: "Databricks", category: "Data Warehouse", region: "North America", segment: "Small", companies: 1190 },
  { tool: "Databricks", category: "Data Warehouse", region: "North America", segment: "Mid", companies: 2362 },
  { tool: "Looker", category: "Business Intelligence", region: "North America", segment: "Enterprise", companies: 905 },
  { tool: "Looker", category: "Business Intelligence", region: "North America", segment: "Small", companies: 1705 },
  { tool: "Looker", category: "Business Intelligence", region: "North America", segment: "Mid", companies: 2977 },
  { tool: "Tableau", category: "Business Intelligence", region: "North America", segment: "Enterprise", companies: 3409 },
  { tool: "Tableau", category: "Business Intelligence", region: "North America", segment: "Small", companies: 6335 },
  { tool: "Tableau", category: "Business Intelligence", region: "North America", segment: "Mid", companies: 11090 },
  { tool: "PowerBI", category: "Business Intelligence", region: "North America", segment: "Enterprise", companies: 3806 },
  { tool: "PowerBI", category: "Business Intelligence", region: "North America", segment: "Small", companies: 6641 },
  { tool: "PowerBI", category: "Business Intelligence", region: "North America", segment: "Mid", companies: 13291 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "North America", segment: "Enterprise", companies: 136 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "North America", segment: "Small", companies: 89 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "North America", segment: "Mid", companies: 171 },
  { tool: "dbt", category: "Data Transformation", region: "North America", segment: "Enterprise", companies: 639 },
  { tool: "dbt", category: "Data Transformation", region: "North America", segment: "Small", companies: 1225 },
  { tool: "dbt", category: "Data Transformation", region: "North America", segment: "Mid", companies: 1985 },
  { tool: "Matillion", category: "Data Transformation", region: "North America", segment: "Enterprise", companies: 173 },
  { tool: "Matillion", category: "Data Transformation", region: "North America", segment: "Small", companies: 138 },
  { tool: "Matillion", category: "Data Transformation", region: "North America", segment: "Mid", companies: 361 },
  { tool: "Dataform", category: "Data Transformation", region: "North America", segment: "Enterprise", companies: 24 },
  { tool: "Dataform", category: "Data Transformation", region: "North America", segment: "Small", companies: 25 },
  { tool: "Dataform", category: "Data Transformation", region: "North America", segment: "Mid", companies: 59 },
  { tool: "Fivetran", category: "Data Ingest", region: "North America", segment: "Enterprise", companies: 224 },
  { tool: "Fivetran", category: "Data Ingest", region: "North America", segment: "Small", companies: 369 },
  { tool: "Fivetran", category: "Data Ingest", region: "North America", segment: "Mid", companies: 767 },
  { tool: "Airbyte", category: "Data Ingest", region: "North America", segment: "Enterprise", companies: 29 },
  { tool: "Airbyte", category: "Data Ingest", region: "North America", segment: "Small", companies: 77 },
  { tool: "Airbyte", category: "Data Ingest", region: "North America", segment: "Mid", companies: 127 },
  { tool: "Matillion", category: "Data Ingest", region: "North America", segment: "Enterprise", companies: 173 },
  { tool: "Matillion", category: "Data Ingest", region: "North America", segment: "Small", companies: 138 },
  { tool: "Matillion", category: "Data Ingest", region: "North America", segment: "Mid", companies: 361 },
  { tool: "Stitch", category: "Data Ingest", region: "North America", segment: "Enterprise", companies: 225 },
  { tool: "Stitch", category: "Data Ingest", region: "North America", segment: "Small", companies: 271 },
  { tool: "Stitch", category: "Data Ingest", region: "North America", segment: "Mid", companies: 484 },
  { tool: "Alation", category: "Data Catalog", region: "North America", segment: "Enterprise", companies: 287 },
  { tool: "Alation", category: "Data Catalog", region: "North America", segment: "Small", companies: 81 },
  { tool: "Alation", category: "Data Catalog", region: "North America", segment: "Mid", companies: 252 },
  { tool: "Atlan", category: "Data Catalog", region: "North America", segment: "Enterprise", companies: 52 },
  { tool: "Atlan", category: "Data Catalog", region: "North America", segment: "Small", companies: 21 },
  { tool: "Atlan", category: "Data Catalog", region: "North America", segment: "Mid", companies: 77 },
  { tool: "Collibra", category: "Data Catalog", region: "North America", segment: "Enterprise", companies: 442 },
  { tool: "Collibra", category: "Data Catalog", region: "North America", segment: "Small", companies: 167 },
  { tool: "Collibra", category: "Data Catalog", region: "North America", segment: "Mid", companies: 415 },
  { tool: "Datahub", category: "Data Catalog", region: "North America", segment: "Enterprise", companies: 110 },
  { tool: "Datahub", category: "Data Catalog", region: "North America", segment: "Small", companies: 40 },
  { tool: "Datahub", category: "Data Catalog", region: "North America", segment: "Mid", companies: 117 },
  { tool: "Amundsen", category: "Data Catalog", region: "North America", segment: "Enterprise", companies: 14 },
  { tool: "Amundsen", category: "Data Catalog", region: "North America", segment: "Small", companies: 7 },
  { tool: "Amundsen", category: "Data Catalog", region: "North America", segment: "Mid", companies: 21 },
  
  // Europe
  { tool: "BigQuery", category: "Data Warehouse", region: "Europe", segment: "Enterprise", companies: 225 },
  { tool: "BigQuery", category: "Data Warehouse", region: "Europe", segment: "Small", companies: 360 },
  { tool: "BigQuery", category: "Data Warehouse", region: "Europe", segment: "Mid", companies: 414 },
  { tool: "Snowflake", category: "Data Warehouse", region: "Europe", segment: "Enterprise", companies: 518 },
  { tool: "Snowflake", category: "Data Warehouse", region: "Europe", segment: "Small", companies: 713 },
  { tool: "Snowflake", category: "Data Warehouse", region: "Europe", segment: "Mid", companies: 1031 },
  { tool: "Redshift", category: "Data Warehouse", region: "Europe", segment: "Enterprise", companies: 222 },
  { tool: "Redshift", category: "Data Warehouse", region: "Europe", segment: "Small", companies: 323 },
  { tool: "Redshift", category: "Data Warehouse", region: "Europe", segment: "Mid", companies: 478 },
  { tool: "Databricks", category: "Data Warehouse", region: "Europe", segment: "Enterprise", companies: 638 },
  { tool: "Databricks", category: "Data Warehouse", region: "Europe", segment: "Small", companies: 611 },
  { tool: "Databricks", category: "Data Warehouse", region: "Europe", segment: "Mid", companies: 956 },
  { tool: "Looker", category: "Business Intelligence", region: "Europe", segment: "Enterprise", companies: 418 },
  { tool: "Looker", category: "Business Intelligence", region: "Europe", segment: "Small", companies: 953 },
  { tool: "Looker", category: "Business Intelligence", region: "Europe", segment: "Mid", companies: 1082 },
  { tool: "Tableau", category: "Business Intelligence", region: "Europe", segment: "Enterprise", companies: 1639 },
  { tool: "Tableau", category: "Business Intelligence", region: "Europe", segment: "Small", companies: 2687 },
  { tool: "Tableau", category: "Business Intelligence", region: "Europe", segment: "Mid", companies: 3355 },
  { tool: "PowerBI", category: "Business Intelligence", region: "Europe", segment: "Enterprise", companies: 2418 },
  { tool: "PowerBI", category: "Business Intelligence", region: "Europe", segment: "Small", companies: 3923 },
  { tool: "PowerBI", category: "Business Intelligence", region: "Europe", segment: "Mid", companies: 5194 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "Europe", segment: "Enterprise", companies: 27 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "Europe", segment: "Small", companies: 38 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "Europe", segment: "Mid", companies: 48 },
  { tool: "dbt", category: "Data Transformation", region: "Europe", segment: "Enterprise", companies: 312 },
  { tool: "dbt", category: "Data Transformation", region: "Europe", segment: "Small", companies: 629 },
  { tool: "dbt", category: "Data Transformation", region: "Europe", segment: "Mid", companies: 808 },
  { tool: "Matillion", category: "Data Transformation", region: "Europe", segment: "Enterprise", companies: 65 },
  { tool: "Matillion", category: "Data Transformation", region: "Europe", segment: "Small", companies: 52 },
  { tool: "Matillion", category: "Data Transformation", region: "Europe", segment: "Mid", companies: 84 },
  { tool: "Dataform", category: "Data Transformation", region: "Europe", segment: "Enterprise", companies: 39 },
  { tool: "Dataform", category: "Data Transformation", region: "Europe", segment: "Small", companies: 47 },
  { tool: "Dataform", category: "Data Transformation", region: "Europe", segment: "Mid", companies: 60 },
  { tool: "Fivetran", category: "Data Ingest", region: "Europe", segment: "Enterprise", companies: 45 },
  { tool: "Fivetran", category: "Data Ingest", region: "Europe", segment: "Small", companies: 157 },
  { tool: "Fivetran", category: "Data Ingest", region: "Europe", segment: "Mid", companies: 163 },
  { tool: "Airbyte", category: "Data Ingest", region: "Europe", segment: "Enterprise", companies: 7 },
  { tool: "Airbyte", category: "Data Ingest", region: "Europe", segment: "Small", companies: 63 },
  { tool: "Airbyte", category: "Data Ingest", region: "Europe", segment: "Mid", companies: 76 },
  { tool: "Matillion", category: "Data Ingest", region: "Europe", segment: "Enterprise", companies: 65 },
  { tool: "Matillion", category: "Data Ingest", region: "Europe", segment: "Small", companies: 52 },
  { tool: "Matillion", category: "Data Ingest", region: "Europe", segment: "Mid", companies: 84 },
  { tool: "Stitch", category: "Data Ingest", region: "Europe", segment: "Enterprise", companies: 53 },
  { tool: "Stitch", category: "Data Ingest", region: "Europe", segment: "Small", companies: 83 },
  { tool: "Stitch", category: "Data Ingest", region: "Europe", segment: "Mid", companies: 119 },
  { tool: "Alation", category: "Data Catalog", region: "Europe", segment: "Enterprise", companies: 59 },
  { tool: "Alation", category: "Data Catalog", region: "Europe", segment: "Small", companies: 21 },
  { tool: "Alation", category: "Data Catalog", region: "Europe", segment: "Mid", companies: 43 },
  { tool: "Atlan", category: "Data Catalog", region: "Europe", segment: "Enterprise", companies: 19 },
  { tool: "Atlan", category: "Data Catalog", region: "Europe", segment: "Small", companies: 10 },
  { tool: "Atlan", category: "Data Catalog", region: "Europe", segment: "Mid", companies: 20 },
  { tool: "Collibra", category: "Data Catalog", region: "Europe", segment: "Enterprise", companies: 184 },
  { tool: "Collibra", category: "Data Catalog", region: "Europe", segment: "Small", companies: 78 },
  { tool: "Collibra", category: "Data Catalog", region: "Europe", segment: "Mid", companies: 159 },
  { tool: "Datahub", category: "Data Catalog", region: "Europe", segment: "Enterprise", companies: 88 },
  { tool: "Datahub", category: "Data Catalog", region: "Europe", segment: "Small", companies: 51 },
  { tool: "Datahub", category: "Data Catalog", region: "Europe", segment: "Mid", companies: 83 },
  { tool: "Amundsen", category: "Data Catalog", region: "Europe", segment: "Enterprise", companies: 4 },
  { tool: "Amundsen", category: "Data Catalog", region: "Europe", segment: "Small", companies: 7 },
  { tool: "Amundsen", category: "Data Catalog", region: "Europe", segment: "Mid", companies: 10 },

  // APAC
  { tool: "BigQuery", category: "Data Warehouse", region: "APAC", segment: "Enterprise", companies: 50 },
  { tool: "BigQuery", category: "Data Warehouse", region: "APAC", segment: "Small", companies: 70 },
  { tool: "BigQuery", category: "Data Warehouse", region: "APAC", segment: "Mid", companies: 94 },
  { tool: "Snowflake", category: "Data Warehouse", region: "APAC", segment: "Enterprise", companies: 135 },
  { tool: "Snowflake", category: "Data Warehouse", region: "APAC", segment: "Small", companies: 211 },
  { tool: "Snowflake", category: "Data Warehouse", region: "APAC", segment: "Mid", companies: 252 },
  { tool: "Redshift", category: "Data Warehouse", region: "APAC", segment: "Enterprise", companies: 92 },
  { tool: "Redshift", category: "Data Warehouse", region: "APAC", segment: "Small", companies: 152 },
  { tool: "Redshift", category: "Data Warehouse", region: "APAC", segment: "Mid", companies: 136 },
  { tool: "Databricks", category: "Data Warehouse", region: "APAC", segment: "Enterprise", companies: 126 },
  { tool: "Databricks", category: "Data Warehouse", region: "APAC", segment: "Small", companies: 188 },
  { tool: "Databricks", category: "Data Warehouse", region: "APAC", segment: "Mid", companies: 214 },
  { tool: "Looker", category: "Business Intelligence", region: "APAC", segment: "Enterprise", companies: 81 },
  { tool: "Looker", category: "Business Intelligence", region: "APAC", segment: "Small", companies: 149 },
  { tool: "Looker", category: "Business Intelligence", region: "APAC", segment: "Mid", companies: 172 },
  { tool: "Tableau", category: "Business Intelligence", region: "APAC", segment: "Enterprise", companies: 340 },
  { tool: "Tableau", category: "Business Intelligence", region: "APAC", segment: "Small", companies: 692 },
  { tool: "Tableau", category: "Business Intelligence", region: "APAC", segment: "Mid", companies: 700 },
  { tool: "PowerBI", category: "Business Intelligence", region: "APAC", segment: "Enterprise", companies: 442 },
  { tool: "PowerBI", category: "Business Intelligence", region: "APAC", segment: "Small", companies: 935 },
  { tool: "PowerBI", category: "Business Intelligence", region: "APAC", segment: "Mid", companies: 1038 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "APAC", segment: "Enterprise", companies: 10 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "APAC", segment: "Small", companies: 6 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "APAC", segment: "Mid", companies: 13 },
  { tool: "dbt", category: "Data Transformation", region: "APAC", segment: "Enterprise", companies: 65 },
  { tool: "dbt", category: "Data Transformation", region: "APAC", segment: "Small", companies: 139 },
  { tool: "dbt", category: "Data Transformation", region: "APAC", segment: "Mid", companies: 136 },
  { tool: "Matillion", category: "Data Transformation", region: "APAC", segment: "Enterprise", companies: 17 },
  { tool: "Matillion", category: "Data Transformation", region: "APAC", segment: "Small", companies: 16 },
  { tool: "Matillion", category: "Data Transformation", region: "APAC", segment: "Mid", companies: 44 },
  { tool: "Dataform", category: "Data Transformation", region: "APAC", segment: "Enterprise", companies: 9 },
  { tool: "Dataform", category: "Data Transformation", region: "APAC", segment: "Small", companies: 7 },
  { tool: "Dataform", category: "Data Transformation", region: "APAC", segment: "Mid", companies: 9 },
  { tool: "Fivetran", category: "Data Ingest", region: "APAC", segment: "Enterprise", companies: 17 },
  { tool: "Fivetran", category: "Data Ingest", region: "APAC", segment: "Small", companies: 27 },
  { tool: "Fivetran", category: "Data Ingest", region: "APAC", segment: "Mid", companies: 46 },
  { tool: "Airbyte", category: "Data Ingest", region: "APAC", segment: "Enterprise", companies: 3 },
  { tool: "Airbyte", category: "Data Ingest", region: "APAC", segment: "Small", companies: 6 },
  { tool: "Airbyte", category: "Data Ingest", region: "APAC", segment: "Mid", companies: 10 },
  { tool: "Matillion", category: "Data Ingest", region: "APAC", segment: "Enterprise", companies: 17 },
  { tool: "Matillion", category: "Data Ingest", region: "APAC", segment: "Small", companies: 16 },
  { tool: "Matillion", category: "Data Ingest", region: "APAC", segment: "Mid", companies: 44 },
  { tool: "Stitch", category: "Data Ingest", region: "APAC", segment: "Enterprise", companies: 23 },
  { tool: "Stitch", category: "Data Ingest", region: "APAC", segment: "Small", companies: 25 },
  { tool: "Stitch", category: "Data Ingest", region: "APAC", segment: "Mid", companies: 31 },
  { tool: "Alation", category: "Data Catalog", region: "APAC", segment: "Enterprise", companies: 25 },
  { tool: "Alation", category: "Data Catalog", region: "APAC", segment: "Small", companies: 10 },
  { tool: "Alation", category: "Data Catalog", region: "APAC", segment: "Mid", companies: 21 },
  { tool: "Atlan", category: "Data Catalog", region: "APAC", segment: "Enterprise", companies: 5 },
  { tool: "Atlan", category: "Data Catalog", region: "APAC", segment: "Small", companies: 0 },
  { tool: "Atlan", category: "Data Catalog", region: "APAC", segment: "Mid", companies: 4 },
  { tool: "Collibra", category: "Data Catalog", region: "APAC", segment: "Enterprise", companies: 45 },
  { tool: "Collibra", category: "Data Catalog", region: "APAC", segment: "Small", companies: 24 },
  { tool: "Collibra", category: "Data Catalog", region: "APAC", segment: "Mid", companies: 37 },
  { tool: "Datahub", category: "Data Catalog", region: "APAC", segment: "Enterprise", companies: 10 },
  { tool: "Datahub", category: "Data Catalog", region: "APAC", segment: "Small", companies: 9 },
  { tool: "Datahub", category: "Data Catalog", region: "APAC", segment: "Mid", companies: 16 },
  { tool: "Amundsen", category: "Data Catalog", region: "APAC", segment: "Enterprise", companies: 0 },
  { tool: "Amundsen", category: "Data Catalog", region: "APAC", segment: "Small", companies: 2 },
  { tool: "Amundsen", category: "Data Catalog", region: "APAC", segment: "Mid", companies: 8 },

  // Uncategorized
  { tool: "BigQuery", category: "Data Warehouse", region: "Uncategorised", segment: "Uncategorised", companies: 5565 },
  { tool: "Snowflake", category: "Data Warehouse", region: "Uncategorised", segment: "Uncategorised", companies: 860 },
  { tool: "Redshift", category: "Data Warehouse", region: "Uncategorised", segment: "Uncategorised", companies: 8951 },
  { tool: "Databricks", category: "Data Warehouse", region: "Uncategorised", segment: "Uncategorised", companies: 3765 },
  { tool: "Looker", category: "Business Intelligence", region: "Uncategorised", segment: "Uncategorised", companies: 0 },
  { tool: "Tableau", category: "Business Intelligence", region: "Uncategorised", segment: "Uncategorised", companies: 82932 },
  { tool: "PowerBI", category: "Business Intelligence", region: "Uncategorised", segment: "Uncategorised", companies: 118403 },
  { tool: "ThoughtSpot", category: "Business Intelligence", region: "Uncategorised", segment: "Uncategorised", companies: 680 },
  { tool: "dbt", category: "Data Transformation", region: "Uncategorised", segment: "Uncategorised", companies: 44312 },
  { tool: "Matillion", category: "Data Transformation", region: "Uncategorised", segment: "Uncategorised", companies: 390 },
  { tool: "Dataform", category: "Data Transformation", region: "Uncategorised", segment: "Uncategorised", companies: 519 },
  { tool: "Fivetran", category: "Data Ingest", region: "Uncategorised", segment: "Uncategorised", companies: 2142 },
  { tool: "Airbyte", category: "Data Ingest", region: "Uncategorised", segment: "Uncategorised", companies: 787 },
  { tool: "Matillion", category: "Data Ingest", region: "Uncategorised", segment: "Uncategorised", companies: 390 },
  { tool: "Stitch", category: "Data Ingest", region: "Uncategorised", segment: "Uncategorised", companies: 2281 },
  { tool: "Alation", category: "Data Catalog", region: "Uncategorised", segment: "Uncategorised", companies: 906 },
  { tool: "Atlan", category: "Data Catalog", region: "Uncategorised", segment: "Uncategorised", companies: 234 },
  { tool: "Collibra", category: "Data Catalog", region: "Uncategorised", segment: "Uncategorised", companies: 2334 },
  { tool: "Datahub", category: "Data Catalog", region: "Uncategorised", segment: "Uncategorised", companies: 933 },
  { tool: "Amundsen", category: "Data Catalog", region: "Uncategorised", segment: "Uncategorised", companies: 123 }
]; 